import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { generateSlug } from "../src/lib/builds/buildNormalizer";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding Hybrid Build System...");

  await prisma.buildReview.deleteMany();
  await prisma.buildCostSnapshot.deleteMany();
  await prisma.buildStats.deleteMany();
  await prisma.buildItem.deleteMany();
  await prisma.build.deleteMany();

  const builds = [
    {
      title: "Battleaxe Solo Open World",
      description: "High sustain melee DPS build for solo open world content. Infinite healing from Mercenary Jacket + Battleaxe Q combo.",
      contentType: "solo_open_world",
      partySize: "1",
      role: "Sustain DPS",
      weaponLine: "Axe",
      mainHand: "Battleaxe",
      offHand: "Torch",
      head: "Hunter Hood",
      chest: "Mercenary Jacket",
      shoes: "Soldier Boots",
      cape: "Thetford Cape",
      food: "Roast Pork",
      potion: "Healing Potion",
      budgetLevel: "cheap",
      difficulty: "easy",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Excellent sustain, cheap to build, great for fame farming, easy to play",
      cons: "Low burst damage, vulnerable to ganks, predictable playstyle",
      combo: "Q (heal) -> W (armor pierce) -> auto attacks -> E (execute)",
      strongAgainst: "Mobs, solo dungeons, open world camps",
      weakAgainst: "Kite builds, ranged DPS in PvP",
      notes: "Mercenary Jacket + Battleaxe Q gives infinite sustain for solo content. Best budget build for new players.",
      tierRecommended: 4,
      enchantRecommended: 0,
      ipMin: 700,
    },
    {
      title: "Bloodletter Solo Mists",
      description: "High burst mobility build for solo mists. Assassin playstyle with strong escape potential.",
      contentType: "solo_mists",
      partySize: "1",
      role: "Mobility build",
      weaponLine: "Dagger",
      mainHand: "Bloodletter",
      offHand: "Mistcaller",
      head: "Mage Cowl",
      chest: "Assassin Jacket",
      shoes: "Soldier Boots",
      cape: "Thetford Cape",
      food: "Beef Stew",
      potion: "Healing Potion",
      budgetLevel: "medium",
      difficulty: "medium",
      status: "experimental",
      sourceType: "hybrid",
      isRecommended: true,
      isPopular: true,
      pros: "High burst damage, great mobility, strong escape potential, good in 1v1",
      cons: "Squishy, requires good positioning, punished hard by mistakes",
      combo: "Q -> W -> E -> auto attacks -> reset with Q",
      strongAgainst: "Immobile builds, healers in 1v1",
      weakAgainst: "Tanks, Nature Staff sustain, chain CC",
      notes: "Best played with Assassin Spike W for extra burst. Save boots for escape.",
      tierRecommended: 6,
      enchantRecommended: 1,
      ipMin: 1100,
    },
    {
      title: "Great Nature Solo Sustain",
      description: "Nearly unkillable sustain build for solo mists. Wins through attrition.",
      contentType: "solo_mists",
      partySize: "1",
      role: "Sustain DPS",
      weaponLine: "Nature Staff",
      mainHand: "Great Nature Staff",
      head: "Mage Cowl",
      chest: "Cleric Robe",
      shoes: "Soldier Boots",
      cape: "Martlock Cape",
      food: "Omelette",
      potion: "Resistance Potion",
      budgetLevel: "medium",
      difficulty: "medium",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Almost unkillable, great sustain, strong 1v1 potential",
      cons: "Low damage output, long fights, weak against purge",
      combo: "Q (thorn) -> W (heal) -> E (root) -> auto attacks -> reposition",
      strongAgainst: "Melee DPS, brawlers, sustained fights",
      weakAgainst: "One-shot builds, purge abilities, mobile assassins",
      notes: "Stay alive and win through attrition. Use Cleric Robe to counter burst.",
      tierRecommended: 6,
      enchantRecommended: 1,
      ipMin: 1000,
    },
    {
      title: "One-handed Cursed Corrupted",
      description: "True damage kite build for corrupted dungeons. Stack curses then detonate.",
      contentType: "corrupted_dungeons",
      partySize: "1",
      role: "Kite DPS",
      weaponLine: "Cursed Staff",
      mainHand: "One-handed Cursed Staff",
      offHand: "Shield",
      head: "Hunter Hood",
      chest: "Cleric Robe",
      shoes: "Soldier Boots",
      cape: "Thetford Cape",
      food: "Beef Stew",
      potion: "Healing Potion",
      budgetLevel: "cheap",
      difficulty: "medium",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "True damage, cheap build, strong against tanks",
      cons: "Skill-shot dependent, vulnerable to interrupts",
      combo: "Q (curse) -> stacks -> E (detonate) -> W (fear)",
      strongAgainst: "Tanks, high armor builds, sustain",
      weakAgainst: "Mobility builds, interrupts, purge",
      notes: "Stack curses then detonate for massive true damage. Shield gives survivability.",
      tierRecommended: 5,
      enchantRecommended: 0,
      ipMin: 900,
    },
    {
      title: "Great Holy Crystal Arena",
      description: "Primary healer build for Crystal Arena 5v5. Strong burst heals with good mana sustain.",
      contentType: "crystal_arena_5v5",
      partySize: "5",
      role: "Healer",
      weaponLine: "Holy Staff",
      mainHand: "Great Holy Staff",
      head: "Cleric Cowl",
      chest: "Cleric Robe",
      shoes: "Scholar Sandals",
      cape: "Lymhurst Cape",
      food: "Omelette",
      potion: "Resistance Potion",
      budgetLevel: "medium",
      difficulty: "medium",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Strong burst heals, good mana sustain, team fight enabler",
      cons: "Vulnerable when focused, predictable, expensive for full build",
      combo: "W (big heal) -> E (AoE heal) -> Q (single target) -> Holy Orb",
      strongAgainst: "Burst comps, sustained damage teams",
      weakAgainst: "Dive comps, purge, interrupt chains",
      notes: "Positioning is key. Stay behind your tank and use Scholar Sandals for mana.",
      tierRecommended: 7,
      enchantRecommended: 1,
      ipMin: 1200,
    },
    {
      title: "Grovekeeper ZvZ Engage Tank",
      description: "The best engage tool in ZvZ. Massive AoE stun sets up wipes for your clap DPS.",
      contentType: "zvz",
      partySize: "20",
      role: "Engage Tank",
      weaponLine: "Hammer",
      mainHand: "Grovekeeper",
      head: "Judicator Helmet",
      chest: "Guardian Armor",
      shoes: "Hunter Shoes",
      cape: "Martlock Cape",
      food: "Pork Omelette",
      potion: "Resistance Potion",
      budgetLevel: "expensive",
      difficulty: "hard",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Best engage in ZvZ, massive AoE stun, sets up wipes",
      cons: "Very expensive, requires good call, single-use engage",
      combo: "E (AoE stun) -> W (slow/armor pierce) -> Q -> reposition",
      strongAgainst: "Clumped teams, defensive formations",
      weakAgainst: "Spread compositions, kiting, Morgana cape",
      notes: "Must be called by shotcaller. Deadly combo with Permafrost or Clap DPS.",
      tierRecommended: 8,
      enchantRecommended: 2,
      ipMin: 1500,
    },
    {
      title: "Permafrost ZvZ Clap DPS",
      description: "Highest clap damage in ZvZ. Freeze, slow and massive AoE burst.",
      contentType: "zvz",
      partySize: "20",
      role: "Clap DPS",
      weaponLine: "Frost Staff",
      mainHand: "Permafrost Prism",
      head: "Royal Cowl",
      chest: "Scholar Robe",
      shoes: "Cleric Sandals",
      cape: "Morgana Cape",
      food: "Beef Stew",
      potion: "Energy Potion",
      budgetLevel: "expensive",
      difficulty: "hard",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Highest clap damage in ZvZ, slow + damage combo",
      cons: "Extremely expensive, needs setup, vulnerable to dives",
      combo: "E (freeze/slow) -> W (damage) -> Q -> Scholar Robe burst",
      strongAgainst: "Clumped teams, static formations",
      weakAgainst: "Dive comps, spread, interrupt chains",
      notes: "Coordinate with engage tank. Royal Cowl gives cooldown reduction for more claps.",
      tierRecommended: 8,
      enchantRecommended: 2,
      ipMin: 1500,
    },
    {
      title: "Double Bladed Miner Escape",
      description: "Fast gathering build focused on escape. Best for gathering in dangerous zones.",
      contentType: "solo_gathering",
      partySize: "1",
      role: "Escape gatherer",
      weaponLine: "Quarterstaff",
      mainHand: "Double Bladed Staff",
      head: "Miner Cap",
      chest: "Miner Garb",
      shoes: "Miner Workboots",
      cape: "Fort Sterling Cape",
      bag: "Gathering Bag",
      mount: "Giant Stag",
      food: "Pork Pie",
      potion: "Invisibility Potion",
      budgetLevel: "medium",
      difficulty: "easy",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Fast gathering, great escape, cheap investment",
      cons: "Zero PvP power, relies on avoiding fights",
      combo: "Q (speed burst) -> W (knockback) -> E (stun) -> run",
      strongAgainst: "Ganking attempts, dangerous zones",
      weakAgainst: "Coordinated gank groups, purges",
      notes: "Double Bladed Staff gives best mobility for escape. Always carry Invis potion for Black Zone.",
      tierRecommended: 5,
      enchantRecommended: 0,
      ipMin: 800,
    },
    {
      title: "Bear Paws Ganking",
      description: "High burst ganking build using Bear Paws. Popular in recent PvP data.",
      contentType: "ganking",
      partySize: "2",
      role: "Ganker",
      weaponLine: "Axe",
      mainHand: "Bear Paws",
      head: "Fiend Cowl",
      chest: "Assassin Jacket",
      shoes: "Royal Sandals",
      cape: "Thetford Cape",
      food: "Beef Stew",
      potion: "Poison Potion",
      budgetLevel: "expensive",
      difficulty: "hard",
      status: "experimental",
      sourceType: "pvp_stats",
      isPopular: true,
      pros: "Extremely high burst, good chase potential, strong in coordinated ganks",
      cons: "Expensive, requires coordination, falls off if initial burst fails",
      combo: "E (leap) -> W (bleed) -> auto attacks -> Royal Sandals reset",
      strongAgainst: "Gatherers, solo players, transporters",
      weakAgainst: "Tanks, healers, organized groups",
      notes: "Coordinate with a partner for best results. Use Fiend Cowl to purge defensives.",
      tierRecommended: 7,
      enchantRecommended: 1,
      ipMin: 1200,
    },
    {
      title: "Bow Solo Mists Cheap",
      description: "Budget-friendly bow build for solo mists. Kite and sustain through Mercenary Jacket.",
      contentType: "solo_mists",
      partySize: "1",
      role: "Kite DPS",
      weaponLine: "Bow",
      mainHand: "Regular Bow",
      head: "Hunter Hood",
      chest: "Mercenary Jacket",
      shoes: "Soldier Boots",
      cape: "Thetford Cape",
      food: "Beef Stew",
      potion: "Healing Potion",
      budgetLevel: "cheap",
      difficulty: "easy",
      status: "active",
      sourceType: "market_calculated",
      isCheap: true,
      pros: "Very cheap, good kiting potential, easy to play",
      cons: "Low burst, outscaled by expensive builds, predictable",
      combo: "Q (slow) -> auto attacks -> W (damage) -> E (escape)",
      strongAgainst: "Melee builds, open world PvE",
      weakAgainst: "One-shot builds, mobile assassins",
      notes: "The cheapest viable build for mists. Focus on positioning and kiting.",
      tierRecommended: 4,
      enchantRecommended: 0,
      ipMin: 700,
    },
    {
      title: "Fire Staff Arena DPS",
      description: "Ranged DPS for Crystal Arena. Consistent sustained damage with good AoE.",
      contentType: "crystal_arena_5v5",
      partySize: "5",
      role: "Ranged DPS",
      weaponLine: "Fire Staff",
      mainHand: "Great Fire Staff",
      head: "Cleric Cowl",
      chest: "Cleric Robe",
      shoes: "Scholar Sandals",
      cape: "Thetford Cape",
      food: "Omelette",
      potion: "Resistance Potion",
      budgetLevel: "medium",
      difficulty: "medium",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Good sustained damage, strong AoE, safe range",
      cons: "Low mobility, vulnerable to dives, skill-shot dependent",
      combo: "Q (fireball) -> W (AoE) -> E (knockback) -> auto attacks",
      strongAgainst: "Clumped teams, defensive compositions",
      weakAgainst: "Dive comps, mobile assassins, interrupts",
      notes: "Stay at max range and poke. Use E to peel divers off you.",
      tierRecommended: 7,
      enchantRecommended: 1,
      ipMin: 1100,
    },
    {
      title: "Mace Defensive Tank",
      description: "Tank for Crystal Arena with heavy defensive tools and peel for your backline.",
      contentType: "crystal_arena_5v5",
      partySize: "5",
      role: "Defensive Tank",
      weaponLine: "Mace",
      mainHand: "Heavy Mace",
      offHand: "Shield",
      head: "Guardian Helmet",
      chest: "Guardian Armor",
      shoes: "Hunter Shoes",
      cape: "Martlock Cape",
      food: "Pork Omelette",
      potion: "Resistance Potion",
      budgetLevel: "medium",
      difficulty: "medium",
      status: "active",
      sourceType: "manual",
      isRecommended: true,
      pros: "Strong peel, good CC, very tanky",
      cons: "Low damage, needs team follow-up",
      combo: "W (stun) -> Q (slow) -> E (armor pierce) -> reposition",
      strongAgainst: "Melee DPS, dive compositions",
      weakAgainst: "Kite comps, sustained damage",
      notes: "Protect your healer and DPS. Use Guardian Armor for team defensive buff.",
      tierRecommended: 7,
      enchantRecommended: 1,
      ipMin: 1300,
    },
  ];

  for (const buildData of builds) {
    const slug = generateSlug(buildData.title);
    const build = await prisma.build.create({
      data: {
        ...buildData,
        slug,
        lastVerifiedAt: new Date(),
        patchVersion: "latest",
      },
    });

    const slotMap: Record<string, string> = {
      main_hand: buildData.mainHand,
      head: buildData.head,
      chest: buildData.chest,
      shoes: buildData.shoes,
    };

    if (buildData.offHand) slotMap.off_hand = buildData.offHand;
    if (buildData.cape) slotMap.cape = buildData.cape;
    if (buildData.bag) slotMap.bag = buildData.bag;
    if (buildData.mount) slotMap.mount = buildData.mount;
    if (buildData.food) slotMap.food = buildData.food;
    if (buildData.potion) slotMap.potion = buildData.potion;

    await prisma.buildItem.createMany({
      data: Object.entries(slotMap).map(([slot, itemName]) => ({
        buildId: build.id,
        slot,
        itemName,
        itemUniqueName: itemName,
        tier: buildData.tierRecommended,
        enchantment: 0,
      })),
    });

    console.log(`  ✓ Created build: ${buildData.title}`);
  }

  console.log(`\nAdding PvP stats for existing builds...`);
  const allBuilds = await prisma.build.findMany();

  const pvpStatsData = [
    { title: "Battleaxe Solo Open World", usages: 320, kills: 180, deaths: 95, assists: 40, winRate: 62.5, fameRatio: 2.1, averageIp: 980, sampleSize: 480, source: "murderledger" },
    { title: "Bloodletter Solo Mists", usages: 520, kills: 310, deaths: 160, assists: 55, winRate: 58.2, fameRatio: 1.8, averageIp: 1150, sampleSize: 680, source: "murderledger" },
    { title: "Great Nature Solo Sustain", usages: 280, kills: 140, deaths: 80, assists: 60, winRate: 65.1, fameRatio: 2.4, averageIp: 1050, sampleSize: 420, source: "albionbattles" },
    { title: "One-handed Cursed Corrupted", usages: 190, kills: 110, deaths: 70, assists: 25, winRate: 55.8, fameRatio: 1.6, averageIp: 920, sampleSize: 310, source: "murderledger" },
    { title: "Bear Paws Ganking", usages: 410, kills: 280, deaths: 130, assists: 70, winRate: 60.3, fameRatio: 2.8, averageIp: 1250, sampleSize: 550, source: "albionbattles" },
    { title: "Bow Solo Mists Cheap", usages: 150, kills: 80, deaths: 55, assists: 20, winRate: 52.4, fameRatio: 1.4, averageIp: 780, sampleSize: 240, source: "murderledger" },
  ];

  let statsAdded = 0;
  for (const statData of pvpStatsData) {
    const matchedBuild = allBuilds.find(b => b.title === statData.title);
    if (!matchedBuild) {
      console.warn(`  ! Build not found for PvP stats: ${statData.title}`);
      continue;
    }
    await prisma.buildStats.create({
      data: {
        buildId: matchedBuild.id,
        source: statData.source,
        contentType: matchedBuild.contentType,
        usages: statData.usages,
        kills: statData.kills,
        deaths: statData.deaths,
        assists: statData.assists,
        winRate: statData.winRate,
        fameRatio: statData.fameRatio,
        averageIp: statData.averageIp,
        sampleSize: statData.sampleSize,
        dateRange: "2026-05-01 to 2026-06-01",
        lastSyncedAt: new Date(),
      },
    });
    statsAdded++;

    if (statData.usages >= 25 && statData.sampleSize >= 25 && statData.winRate >= 50 && !matchedBuild.isPopular) {
      await prisma.build.update({
        where: { id: matchedBuild.id },
        data: { isPopular: true, sourceType: matchedBuild.sourceType === "manual" ? "hybrid" : matchedBuild.sourceType },
      });
    }
  }
  console.log(`  ✓ Added stats for ${statsAdded} builds`);

  console.log(`\nSeeded ${builds.length} builds with ${statsAdded} PvP stat records successfully!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
